./00_Resources.sh
./01_battery_control.sh
./1_secure_cron.sh
./2_net-tools.sh
./3_libpam.sh
./4_common-password.sh
./5_login_defs.sh
./6_access_conf.sh
./7_umask.sh
./8_secure_important_files.sh
./9_partitions_conf.sh
./10_sysctl_conf.sh
./11_auditd.sh
./13_secure_boot.sh
./14_disable_ssh.sh
./15_aide.sh
./16_antivirus.sh
./18_stacer.sh
./19_virtualbox.sh
./20_marktext.sh
./22_kde_wallet.sh
./23_firewall.sh
./24_GetSystemInfos.sh
./26_Docker.sh
./28_auto_security_updates.sh
./29_clean_package_cache.sh
./30_Disable_dumps.sh
./31_fail2ban.sh
./32_accounting_on.sh
./33_banner.sh
./34_install_rkhunter.sh
./35_logging.sh
./36_printing.sh
